WIP: Add support for ECHO 11
It fails with the following error:

```
2.2.4 :002 > DDEX::ECHO.read("ExampleManifest.xml")
first check
second check
LoadError: cannot load such file -- java/io/serializable
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/Code/Beatroot/ddex/net/ddex/xml/v2011/amep/v11/key_info.rb:13:in `<top (required)>'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/Code/Beatroot/ddex/net/ddex/xml/v2011/amep/v11/ddex_digital_signature.rb:13:in `<top (required)>'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/Code/Beatroot/ddex/net/ddex/xml/v2011/amep/v11/ws_message_header.rb:13:in `<top (required)>'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo/v11/delivery_frequency_change_request_message.rb:14:in `<top (required)>'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex.rb:90:in `block in require_standard'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex.rb:90:in `each'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex.rb:90:in `require_standard'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo/v11.rb:8:in `<module:V11>'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo/v11.rb:6:in `<module:ECHO>'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo/v11.rb:5:in `<module:DDEX>'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo/v11.rb:4:in `<top (required)>'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo.rb:116:in `const_get'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo.rb:116:in `load_version'
	from /Users/ancor/Code/Beatroot/ddex/lib/ddex/echo.rb:39:in `read'
	from (irb):2
```